/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class REGISTRATION_SYSTEM extends javax.swing.JFrame {

    /**
     * Creates new form REGISTRATION_SYSTEM
     */
    public REGISTRATION_SYSTEM() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Fname = new javax.swing.JTextField();
        jTextField_Lname = new javax.swing.JTextField();
        jTextField_RegNo = new javax.swing.JTextField();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jTextField_Phone = new javax.swing.JTextField();
        jTextField_Parent_Phone = new javax.swing.JTextField();
        jComboBox_year = new javax.swing.JComboBox<>();
        jComboBox_semester = new javax.swing.JComboBox<>();
        jComboBox_School = new javax.swing.JComboBox<>();
        jComboBox_Course = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton_Register = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jTextField_Year = new javax.swing.JTextField();
        jTextField_School = new javax.swing.JTextField();
        jTextField_Course = new javax.swing.JTextField();
        jTextField_semester = new javax.swing.JTextField();
        jButton_Set = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Employee_Number = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_TOTALFEE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_FEEPAID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_FEEBALANCE = new javax.swing.JTextField();
        jButton_FEEBALANCE = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_COURSEEVALUATION = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRATION FORM");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FIRST NAME");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("LAST NAME");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("REG NUMBER");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("GENDER");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("PASSWORD");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("PHONE");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("GUARDIAN NO");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("YEAR OF STUDY");

        jRadioButton_Male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton_Male.setText("MALE");

        jRadioButton_Female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton_Female.setText("FEMALE");

        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });

        jComboBox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year One", "Year Two", "Year Three", "Year Four" }));

        jComboBox_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester One", "Semester Two", "Semester Three" }));

        jComboBox_School.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIST", "BCOM", "SPAS", "SASS", "SEDHURED", "SHSS", "SCHOOL OF LAW", "SCHOOL OF MEDICINE", "SCHOOL OF AGRICULTURE" }));
        jComboBox_School.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SchoolActionPerformed(evt);
            }
        });

        jComboBox_Course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BIT", "ACMP", "SOEN", "COMP", "NURSING", "LAW", "ENGLISH LITERATURE", "BIO AGRICULTURE", " " }));
        jComboBox_Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CourseActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("SCHOOL");

        jButton_Register.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Register.setText("REGISTER");
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        jButton_Update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Update.setText("UPDATE");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Delete.setText("DELETE A RECORD");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Set.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Set.setText("CLICK HERE TO SET THE VALUES OF YEAR SEMESTER SCHOOL COURSE AND UNITS");
        jButton_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SetActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("EMAIL ADDRESS");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("EMPLOYEE NUMBER");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("TOTAL FEE PAYABLE");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("FEE PAID");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("FEE BALANCE");

        jButton_FEEBALANCE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_FEEBALANCE.setText("CALCULATE FEE BALANCE");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("COURSE EVALUATION");

        jTextArea_COURSEEVALUATION.setColumns(20);
        jTextArea_COURSEEVALUATION.setRows(5);
        jScrollPane1.setViewportView(jTextArea_COURSEEVALUATION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Parent_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton_Delete)
                                            .addGap(51, 51, 51))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField_Lname, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                    .addComponent(jTextField_Fname))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField_Employee_Number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                    .addComponent(jTextField_RegNo, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addGap(53, 53, 53)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Male)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_Female)
                                        .addGap(448, 448, 448)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_School, 0, 1, Short.MAX_VALUE)
                                    .addComponent(jComboBox_year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_TOTALFEE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextField_FEEBALANCE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Register)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_Update))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_FEEBALANCE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_Set, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_School, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(jTextField_Year, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField_FEEPAID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_School, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_School, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_Employee_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_TOTALFEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_FEEPAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_RegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_FEEBALANCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_FEEBALANCE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jRadioButton_Male)
                                    .addComponent(jRadioButton_Female))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16)
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addComponent(jButton_Set)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Parent_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Register)
                    .addComponent(jButton1))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_SchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_SchoolActionPerformed

    private void jComboBox_CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_CourseActionPerformed
     //creating a function to verify the empty fields
    public boolean verifyTheFields() {
        String firstname = jTextField_Fname.getText();
        String lastname= jTextField_Lname.getText();
        String Phone = jTextField_Phone.getText();
        String RegNo=jTextField_RegNo.getText();
        String Gender=jRadioButton_Male.getText();
        String year=jTextField_Year.getText();
        String Semester =jTextField_semester.getText();
        String School=jTextField_School.getText();
        String Course=jTextField_Course.getText();
        String Password = String.valueOf(jPasswordField_Password.getPassword());
        
        //checking empty fields
        if (firstname.trim().equals("") || lastname.trim().equals("") || Phone.trim().equals("") || Password.trim().equals("")
                || RegNo.trim().equals("")||Gender.trim().equals("")||year.trim().equals("")||Semester.trim().equals("")||School.trim().equals("")||Course.trim().equals("")) {

            JOptionPane.showMessageDialog(null, "One or more of the fields are Empty", "Empty Fields", 10);
            return false;
        }else  {
            return false;
        }}
    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
         String firstname=jTextField_Fname.getText();
        String lastname=jTextField_Lname.getText();
        String RegNo=jTextField_RegNo.getText();
        String Gender=jRadioButton_Male.getText();
       
        String Password=String.valueOf(jPasswordField_Password.getPassword());
        String Phone=jTextField_Phone.getText();
        String Guardian_phone=jTextField_Parent_Phone.getText();
         String year=jTextField_Year.getText();
        String Semester =jTextField_semester.getText();
        String School=jTextField_School.getText();
        String Course=jTextField_Course.getText();
        if (jRadioButton_Female.isSelected() ){
     Gender="Female";
     }
        else{Gender="Male";}
        if (firstname.trim().equals("") || lastname.trim().equals("") || Phone.trim().equals("") || Password.trim().equals("")
                || RegNo.trim().equals("")||Gender.trim().equals("")||year.trim().equals("")||Semester.trim().equals("")||School.trim().equals("")||Course.trim().equals("")) {

            JOptionPane.showMessageDialog(null, "One or more of the fields are Empty", "Empty Fields", 10);
            //return false;
        }
        try {
           
            Class.forName("com.mysql.jdbc.Driver");
           Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/university data","root","");
           PreparedStatement ps=conn.prepareStatement("INSERT into register(firstname ,lastname,Regno,gender,password,Phone,Guardian_phone,Year_of_study,Semester,School,Course)Values(?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,firstname );
           ps.setString(2,lastname );
           ps.setString(3,RegNo );
           ps.setString(4,Gender );
           //ps.setString(5,Gendr );
           ps.setString(5,Password );
           ps.setString(6,Phone );
           ps.setString(7,Guardian_phone );
           ps.setString(8,year );
           ps.setString(9,Semester );
           ps.setString(10,School );
           ps.setString(11,Course );
           if(jRadioButton_Male.isSelected()){
           ps.setString(4, jRadioButton_Male.getText());
           }else ps.setString(4, jRadioButton_Female.getText());
           
           ps.executeUpdate();
           JOptionPane.showMessageDialog(this, "Your registration is successful");
        } catch (Exception ex) {
           /* Logger.getLogger(REGISTRATION_SYSTEM.class.getName()).log(Level.SEVERE, null, ex);*/
           JOptionPane.showMessageDialog(null, "One or more of the fields are Empty", "Empty Fields", 10);
            //return false;
        }
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        String firstname=jTextField_Fname.getText();
        //String lastname=jTextField_Lname.getText();
        String RegNo=jTextField_RegNo.getText();
        //String Gender=jRadioButton_Male.getText();
        //String Gendr=jRadioButton_Female.getText();
        //String Password=String.valueOf(jPasswordField_Password.getPassword());
        //String Phone=jTextField_Phone.getText();
        //String Guardian_phone=jTextField_Parent_Phone.getText();
        //String year=jTextField_Year.getText();
        //String Semester =jTextField_semester.getText();
        //String School=jTextField_School.getText();
        //String Course=jTextField_Course.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
           Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/university data","root","");
           PreparedStatement ps=conn.prepareStatement("DELETE FROM register WHERE firstname=? AND Regno=?");
           ps.setString(1,firstname );
           //ps.setString(2,lastname );
           ps.setString(2,RegNo );
           //ps.setString(4,Gender );
           //ps.setString(5,Gendr );
           //ps.setString(6,Password );
           //ps.setString(7,Phone );
           //ps.setString(8,Guardian_phone );
           //ps.setString(9,year );
           //ps.setString(10,Semester );
           //ps.setString(11,School );
           //ps.setString(12,Course );
           ps.executeUpdate();
           JOptionPane.showMessageDialog(this, "The record is deleted successfully");
        } catch (Exception ex) {
            Logger.getLogger( REGISTRATION_SYSTEM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SetActionPerformed
        jTextField_Year.setText(jComboBox_year.getSelectedItem().toString());
        jTextField_semester.setText(jComboBox_semester.getSelectedItem().toString());
        jTextField_School.setText(jComboBox_School.getSelectedItem().toString());
        jTextField_Course.setText(jComboBox_Course.getSelectedItem().toString());
                        
    }//GEN-LAST:event_jButton_SetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          jTextField_Fname.setText("");
         jTextField_Lname.setText("");
         jTextField_RegNo.setText("");
         //jRadioButton_Male.setText("");
        //jRadioButton_Female.setText("");
       jPasswordField_Password.setText("");
       jTextField_Phone.setText("");
        jTextField_Parent_Phone.setText("");
        jTextField_Year.setText("");
        jTextField_semester.setText("");
        jTextField_School.setText("");
        jTextField_Course.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
       try {
        String firstname=jTextField_Fname.getText();
        String lastname=jTextField_Lname.getText();
        String RegNo=jTextField_RegNo.getText();
        //String Gender=jRadioButton_Male.getText();
        //String Gendr=jRadioButton_Female.getText();
        String Password=String.valueOf(jPasswordField_Password.getPassword());
        String Phone=jTextField_Phone.getText();
        String Guardian_phone=jTextField_Parent_Phone.getText();
        String year=jTextField_Year.getText();
        String Semester =jTextField_semester.getText();
        String School=jTextField_School.getText();
        String Course=jTextField_Course.getText();
            Class.forName("com.mysql.jdbc.Driver");
           Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/university data","root","");
           PreparedStatement ps=conn.prepareStatement("UPDATE register SET firstname=?,lastname=?,Password=?,gender=?,Phone=?,Guardian_phone=?,Year_of_study=?, Semester=?,School=?, Course=? WHERE RegNo=?");
           ps.setString(1, firstname);
           ps.setString(2, lastname);
           ps.setString(3, Password);
           ps.setString(5, Phone);
           ps.setString(6, Guardian_phone);
           ps.setString(7, year);
           ps.setString(8, Semester);
           ps.setString(9, School);
           ps.setString(10, Course);
           ps.setString(11, RegNo);
           //ps.setString(12, name);
           //ps.setString(2, Age);
           if(jRadioButton_Male.isSelected()){
           ps.setString(4, jRadioButton_Male.getText());
           }else ps.setString(4, jRadioButton_Female.getText());
           //ps.setString(4, Id);
           ps.executeUpdate();
           JOptionPane.showMessageDialog(this, "Details updated successfully");
        } catch (Exception ex) {
            Logger.getLogger(REGISTRATION_SYSTEM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION_SYSTEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRATION_SYSTEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_FEEBALANCE;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JButton jButton_Set;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_Course;
    private javax.swing.JComboBox<String> jComboBox_School;
    private javax.swing.JComboBox<String> jComboBox_semester;
    private javax.swing.JComboBox<String> jComboBox_year;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_COURSEEVALUATION;
    private javax.swing.JTextField jTextField_Course;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Employee_Number;
    private javax.swing.JTextField jTextField_FEEBALANCE;
    private javax.swing.JTextField jTextField_FEEPAID;
    private javax.swing.JTextField jTextField_Fname;
    private javax.swing.JTextField jTextField_Lname;
    private javax.swing.JTextField jTextField_Parent_Phone;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_RegNo;
    private javax.swing.JTextField jTextField_School;
    private javax.swing.JTextField jTextField_TOTALFEE;
    private javax.swing.JTextField jTextField_Year;
    private javax.swing.JTextField jTextField_semester;
    // End of variables declaration//GEN-END:variables
}
