/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegisterUnits;

import StudentPage.studentpage;
import javax.swing.JOptionPane;

/**
 *
 * @author BASIL
 */
public class registerunits extends javax.swing.JFrame {

    /**
     * Creates new form units
     */
    public registerunits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        unit1 = new javax.swing.JLabel();
        unit2 = new javax.swing.JLabel();
        unit3 = new javax.swing.JLabel();
        unit4 = new javax.swing.JLabel();
        unit5 = new javax.swing.JLabel();
        unit6 = new javax.swing.JLabel();
        SearchUnits = new javax.swing.JButton();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        check5 = new javax.swing.JCheckBox();
        check6 = new javax.swing.JCheckBox();
        Register = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Register Units");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Student  is Expected to select the units to register for the current semester ");

        year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));

        semester.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem 1", "Sem 2" }));

        unit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unit1.setText("PHIL 104 (Core)");

        unit2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unit2.setText("COMP 107 (Core)");

        unit3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unit3.setText("COMP 103 (Core)");

        unit4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unit4.setText("MATH 112 (Core)");

        unit5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unit5.setText("ZOOL 143 (Core)");

        unit6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unit6.setText("COMS 101 (Core)");

        SearchUnits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchUnits.setText("Search Units");
        SearchUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUnitsActionPerformed(evt);
            }
        });

        Register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
         Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(unit2)
                                .addComponent(unit1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unit3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(unit5)
                                        .addComponent(unit4)
                                        .addComponent(unit6)))))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check1)
                            .addComponent(check2)
                            .addComponent(check3)
                            .addComponent(check4)
                            .addComponent(check5)
                            .addComponent(check6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(SearchUnits))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register)
                .addGap(90, 90, 90)
                .addComponent(Back)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SearchUnits)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(check1)
                    .addComponent(unit1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(check2)
                    .addComponent(unit2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit3)
                    .addComponent(check3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit4)
                    .addComponent(check4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unit5)
                        .addGap(24, 24, 24)
                        .addComponent(unit6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check5)
                        .addGap(18, 18, 18)
                        .addComponent(check6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register)
                    .addComponent(Back))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUnitsActionPerformed
        // TODO add your handling code here:
        if(year.getSelectedItem().equals("Year 1") && semester.getSelectedItem().equals("Sem 1")){
            unit1.setText("PHIL 104 (Core)");
            unit2.setText("COMP 107 (Core)");
            unit3.setText("COMP 103 (Core)");
            unit4.setText("MATH 112 (Core)");
            unit5.setText("ZOOL 143 (Core)");
            unit6.setText("COMS 101 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 1") && semester.getSelectedItem().equals("Sem 2")){
            unit1.setText("COMP 100 (Core)");
            unit2.setText("COMP 102 (Core)");
            unit3.setText("COMP 113 (Core)");
            unit4.setText("MATH 141 (Core)");
            unit5.setText("PHYS 123 (Core)");
            unit6.setText("COMP 121 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 2") && semester.getSelectedItem().equals("Sem 1")){
            unit1.setText("COMP 200 (Core)");
            unit2.setText("COMP 220 (Core)");
            unit3.setText("COMP 204 (Core)");
            unit4.setText("COMP 240 (Core)");
            unit5.setText("COMP 201 (Core)");
            unit6.setText("COMP 212 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 2") && semester.getSelectedItem().equals("Sem 2")){
            unit1.setText("COMP 202 (Core)");
            unit2.setText("COMP 203 (Core)");
            unit3.setText("COMP 205 (Core)");
            unit4.setText("COMP 206 (Core)");
            unit5.setText("COMP 207 (Core)");
            unit6.setText("COMP 240 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 3") && semester.getSelectedItem().equals("Sem 1")){
            unit1.setText("COMP 330 (Core)");
            unit2.setText("COMP 303 (Core)");
            unit3.setText("COMP 301 (Core)");
            unit4.setText("COMP 315 (Core)");
            unit5.setText("COMP 314 (Core)");
            unit6.setText("COMP 305 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 3") && semester.getSelectedItem().equals("Sem 2")){
            unit1.setText("COMP 389 (Core)");
            unit2.setText("COMP 340 (Core)");
            unit3.setText("COMP 320 (Core)");
            unit4.setText("COMP 313 (Core)");
            unit5.setText("COMP 350 (Core)");
            unit6.setText("COMP 323 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 4") && semester.getSelectedItem().equals("Sem 1")){
            unit1.setText("COMP 413 (Core)");
            unit2.setText("COMP 420 (Core)");
            unit3.setText("COMP 404 (Core)");
            unit4.setText("COMP 440 (Core)");
            unit5.setText("COMP 401 (Core)");
            unit6.setText("COMP 415 (Core)");
        }
        else if(year.getSelectedItem().equals("Year 4") && semester.getSelectedItem().equals("Sem 2")){
            unit1.setText("COMP 483 (Core)");
            unit2.setText("COMP 489 (Core)");
            unit3.setText("COMP 449 (Core)");
            unit4.setText("COMP 480 (Core)");
            unit5.setText("COMP 431 (Core)");
            unit6.setText("COMP 495 (Core)");
        }
    }//GEN-LAST:event_SearchUnitsActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        if(check1.isSelected() && check2.isSelected() && check3.isSelected() && check4.isSelected() && check5.isSelected() && check6.isSelected()){
        check1.setSelected(false);
        check2.setSelected(false);
        check3.setSelected(false);
        check4.setSelected(false);
        check5.setSelected(false);
        check6.setSelected(false);
        year.setSelectedItem("Year 1");
        semester.setSelectedItem("Sem 1");
        unit1.setText("PHIL 104 (Core)");
        unit2.setText("COMP 107 (Core)");
        unit3.setText("COMP 103 (Core)");
        unit4.setText("MATH 112 (Core)");
        unit5.setText("ZOOL 143 (Core)");
        unit6.setText("COMS 101 (Core)");
        JOptionPane.showMessageDialog(this, "Units Submitted Successfully awaiting Approval by the CoD");
        }else{
            JOptionPane.showMessageDialog(null, "Select all the core Units for Registration", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        studentpage s = new studentpage();
        s.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerunits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerunits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerunits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerunits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerunits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Register;
    private javax.swing.JButton SearchUnits;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JCheckBox check6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JLabel unit1;
    private javax.swing.JLabel unit2;
    private javax.swing.JLabel unit3;
    private javax.swing.JLabel unit4;
    private javax.swing.JLabel unit5;
    private javax.swing.JLabel unit6;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
