/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentPage;

import Login.LoginInterface;
import RegisterUnits.registerunits;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author BASIL
 */
public class studentpage extends javax.swing.JFrame {

    /**
     * Creates new form studentpage
     */
    
    public studentpage() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmpRegNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        FeeBalance = new javax.swing.JTextField();
        RegisterUnits = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        UnitsApprovedMessage = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        Course = new javax.swing.JLabel();
        RegistrationInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        EmpRegNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EmpRegNo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RegNo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        EmpRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpRegNoActionPerformed(evt);
            }
        });
        EmpRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpRegNoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel1.setText("Fee Balance : ");

        FeeBalance.setEditable(false);
        FeeBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FeeBalance.setText("Ksh. ");
        FeeBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeeBalanceActionPerformed(evt);
            }
        });

        RegisterUnits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterUnits.setText("Register Units");
        RegisterUnits.setEnabled(false);
        RegisterUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUnitsActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        UnitsApprovedMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        LastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNameFocusGained(evt);
            }
        });

        Year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Course.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        RegistrationInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(FeeBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(RegisterUnits)
                        .addGap(34, 34, 34)
                        .addComponent(Back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(EmpRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Course, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnitsApprovedMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RegistrationInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmpRegNo)
                    .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Course, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(RegistrationInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UnitsApprovedMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(FeeBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpRegNoActionPerformed
    
   
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginInterface s = new LoginInterface();
        s.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void RegisterUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUnitsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        registerunits s = new registerunits();
        s.setVisible(true);
    }//GEN-LAST:event_RegisterUnitsActionPerformed

    private void FeeBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeeBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeeBalanceActionPerformed

    private void LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFocusGained

    private void EmpRegNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpRegNoKeyPressed
        // TODO add your handling code here:
        //InputMap im = (InputMap)UIManager.get("GetInfo.focusInputMap");
        InputMap im = EmpRegNo.getInputMap();
        im.put(KeyStroke.getKeyStroke("ENTER"), "pressed");
        im.put(KeyStroke.getKeyStroke("released ENTER"), "released");
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentlogindata", "root", "");
                    PreparedStatement ps = con.prepareStatement("SELECT * FROM student WHERE EmpRegNo=?");
                    ps.setString(1, EmpRegNo.getText());

                    ResultSet rst = ps.executeQuery();
                    if (rst.next()){
                            LastName.setText("Welcome " + rst.getString("LastName"));
                            FeeBalance.setText(rst.getString("FeeBalance"));
                            Year.setText("Year : " + rst.getString("Year"));
                            Course.setText(rst.getString("Course"));

                        if(FeeBalance.getText() == "0" || FeeBalance.getText().startsWith("-")){
                                RegistrationInfo.setForeground(Color.GREEN);
                                RegistrationInfo.setText("You Are Eligible to register for units");
                                UnitsApprovedMessage.setText("Units Pending Approval!!!!");
                                JOptionPane.showMessageDialog(null, "You Are Eligible to Register for Units");
                                RegisterUnits.setEnabled(true);
                                
                        }else{
                            RegistrationInfo.setForeground(Color.RED);
                            RegistrationInfo.setText("You Are Not Eligible to Register for Units");
                            UnitsApprovedMessage.setText("Units Pending Approval!!!!");
                            JOptionPane.showMessageDialog(null, "     Complete Fee first!!!     ", "Fee", JOptionPane.ERROR_MESSAGE);
                            RegisterUnits.setEnabled(false);
                    }
                
            }
        }catch(Exception h){
            System.out.println(h);
        }
        }
    }//GEN-LAST:event_EmpRegNoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Course;
    private javax.swing.JTextField EmpRegNo;
    private javax.swing.JTextField FeeBalance;
    private javax.swing.JLabel LastName;
    private javax.swing.JButton RegisterUnits;
    private javax.swing.JLabel RegistrationInfo;
    private javax.swing.JLabel UnitsApprovedMessage;
    private javax.swing.JLabel Year;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
