/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RegistrationSystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import university.system.REGISTRATION_SYSTEM;

/**
 *
 * @author PC
 */
public class REGISTRATION extends javax.swing.JFrame {

    /**
     * Creates new form REGISTRATION
     */
    public REGISTRATION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_FIRSTNAME = new javax.swing.JTextField();
        jTextField_LASTNAME = new javax.swing.JTextField();
        jTextField_EmpRegNo = new javax.swing.JTextField();
        jTextField_EMAILADRESS = new javax.swing.JTextField();
        jTextField_PHONENUMBER = new javax.swing.JTextField();
        jPasswordField_PASSWORD = new javax.swing.JPasswordField();
        jTextField_GUARDIANPHONE = new javax.swing.JTextField();
        jRadioButton_MALE = new javax.swing.JRadioButton();
        jRadioButton_FEMALE = new javax.swing.JRadioButton();
        jButton_ADDARECORD = new javax.swing.JButton();
        jButton_UPDATEARECORD = new javax.swing.JButton();
        jButton_DELETEARECORD = new javax.swing.JButton();
        jButton_CLEARTEXT = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTER HERE");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FIRST NAME");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("LAST NAME");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("GENDER");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("EMP/REG NO.");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("EMAIL ADRESS");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("PASSWORD");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText(" PHONE NUMBER");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("GUARDIAN PHONE");

        jTextField_FIRSTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FIRSTNAMEActionPerformed(evt);
            }
        });

        jTextField_LASTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LASTNAMEActionPerformed(evt);
            }
        });

        jTextField_EmpRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmpRegNoActionPerformed(evt);
            }
        });

        jRadioButton_MALE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton_MALE.setText("MALE");

        jRadioButton_FEMALE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton_FEMALE.setText("FEMALE");

        jButton_ADDARECORD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_ADDARECORD.setText("ADD A RECORD");
        jButton_ADDARECORD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ADDARECORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ADDARECORDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ADDARECORDMouseExited(evt);
            }
        });
        jButton_ADDARECORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADDARECORDActionPerformed(evt);
            }
        });

        jButton_UPDATEARECORD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_UPDATEARECORD.setText("UPDATE A RECORD");
        jButton_UPDATEARECORD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_UPDATEARECORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_UPDATEARECORDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_UPDATEARECORDMouseExited(evt);
            }
        });
        jButton_UPDATEARECORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UPDATEARECORDActionPerformed(evt);
            }
        });

        jButton_DELETEARECORD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_DELETEARECORD.setText("DELETE A RECORD");
        jButton_DELETEARECORD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_DELETEARECORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_DELETEARECORDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_DELETEARECORDMouseExited(evt);
            }
        });
        jButton_DELETEARECORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DELETEARECORDActionPerformed(evt);
            }
        });

        jButton_CLEARTEXT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_CLEARTEXT.setText("CLEAR TEXT");
        jButton_CLEARTEXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_CLEARTEXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CLEARTEXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CLEARTEXTMouseExited(evt);
            }
        });
        jButton_CLEARTEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CLEARTEXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(136, 136, 136)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_FIRSTNAME)
                                            .addComponent(jTextField_LASTNAME)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton_MALE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                                .addComponent(jRadioButton_FEMALE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(111, 111, 111)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_EmpRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_EMAILADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_PHONENUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_GUARDIANPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton_UPDATEARECORD)
                                                .addGap(60, 60, 60)
                                                .addComponent(jButton_DELETEARECORD))))))
                            .addComponent(jButton_ADDARECORD))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton_CLEARTEXT)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_FIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_LASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton_MALE)
                    .addComponent(jRadioButton_FEMALE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_EmpRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_EMAILADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_PHONENUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_GUARDIANPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ADDARECORD)
                    .addComponent(jButton_UPDATEARECORD)
                    .addComponent(jButton_DELETEARECORD)
                    .addComponent(jButton_CLEARTEXT))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CLEARTEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CLEARTEXTActionPerformed
         jTextField_FIRSTNAME.setText("");
         jTextField_LASTNAME.setText("");
         //jRadioButton_MALE.setText("");
        //jRadioButton_FEMALE.setText("");
       
       jTextField_EmpRegNo.setText("");
        
        jTextField_EMAILADRESS.setText("");
        jPasswordField_PASSWORD.setText("");
        jTextField_PHONENUMBER.setText("");
        jTextField_GUARDIANPHONE.setText("");
    }//GEN-LAST:event_jButton_CLEARTEXTActionPerformed

    private void jButton_CLEARTEXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CLEARTEXTMouseEntered
        jButton_CLEARTEXT.setForeground(Color.white);
        jButton_CLEARTEXT.setBackground(Color.BLUE);
    }//GEN-LAST:event_jButton_CLEARTEXTMouseEntered

    private void jButton_CLEARTEXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CLEARTEXTMouseExited
        jButton_CLEARTEXT.setForeground(Color.black);
        jButton_CLEARTEXT.setBackground(Color.gray);
    }//GEN-LAST:event_jButton_CLEARTEXTMouseExited

    private void jButton_DELETEARECORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DELETEARECORDActionPerformed
     String RegEmpNo=jTextField_EmpRegNo.getText();
        
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/studentlogindata", "root", "");
           PreparedStatement ps=conn.prepareStatement("DELETE FROM registrationdetails WHERE RegEmpNo=?");
           ps.setString(1,RegEmpNo );
           
          
           
           ps.executeUpdate();
           JOptionPane.showMessageDialog(this, "The record is deleted successfully");
        } catch (Exception ex) {
            //Logger.getLogger( REGISTRATION_SYSTEM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_DELETEARECORDActionPerformed

    private void jButton_DELETEARECORDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DELETEARECORDMouseEntered
       jButton_DELETEARECORD.setForeground(Color.white);
        jButton_DELETEARECORD.setBackground(Color.red);
    }//GEN-LAST:event_jButton_DELETEARECORDMouseEntered

    private void jButton_DELETEARECORDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DELETEARECORDMouseExited
         jButton_DELETEARECORD.setForeground(Color.black);
        jButton_DELETEARECORD.setBackground(Color.gray);
    }//GEN-LAST:event_jButton_DELETEARECORDMouseExited

    private void jButton_ADDARECORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADDARECORDActionPerformed
        
        String firstname = jTextField_FIRSTNAME.getText();
        String lastname = jTextField_LASTNAME.getText();
        String Gender = jRadioButton_MALE.getText();
        String EMPLOYEENUM = jTextField_EmpRegNo.getText();
        String RegNo = jTextField_EmpRegNo.getText();
         String EMAILADRESS =  jTextField_EMAILADRESS.getText();
        String Password = String.valueOf(jPasswordField_PASSWORD.getText());
        String Phone =  jTextField_PHONENUMBER.getText();
        String Guardian_phone = jTextField_GUARDIANPHONE.getText();
         
        if (jRadioButton_FEMALE.isSelected() ){
     Gender="Female";
     } else{
            Gender="Male";
        }
        
        
         if (jTextField_FIRSTNAME.getText().trim().equals("") || jTextField_LASTNAME.getText().trim().equals("") || jRadioButton_MALE.getText().trim().equals("") || jTextField_EmpRegNo.getText().trim().equals("")
                || jTextField_EMAILADRESS.getText().trim().equals("")||jPasswordField_PASSWORD.getText().trim().equals("")||jTextField_PHONENUMBER.getText().trim().equals("")||jTextField_GUARDIANPHONE.getText().trim().equals("")) {

            JOptionPane.showMessageDialog(null, "One or more of the fields are Empty", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
        }else{
             
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/studentlogindata", "root", "");
           PreparedStatement ps=conn.prepareStatement("INSERT INTO registrationdetails(fname, lname, Gender, Email, Password, Phone, GurdianNo, RegEmpNo) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            
           ps.setString(1,firstname);
           ps.setString(2,lastname );
           ps.setString(3,Gender);
           //ps.setString(5,Gendr );
           ps.setString(4,EMAILADRESS );
           ps.setString(5,Password  );
           ps.setString(6,Phone);
           ps.setString(7,Guardian_phone );
           ps.setString(8, RegNo);
           
           if (RegNo.contains(jTextField_EmpRegNo.getText())){
               JOptionPane.showMessageDialog(null, "   Registration Number is Already registered!!   ", "ERROR!", JOptionPane.ERROR_MESSAGE);
           }
           
           if(jRadioButton_MALE.isSelected()){
           ps.setString(3, jRadioButton_MALE.getText());
           }else {
               ps.setString(3, jRadioButton_FEMALE.getText());
           }
           
           ps.execute();
           JOptionPane.showMessageDialog(this, "Your registration is successful");
           ps.close();
           conn.close();
        } catch (Exception ex) {
         
           //JOptionPane.showMessageDialog(this, "An error occured while registering your details", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
           
        }
    }//GEN-LAST:event_jButton_ADDARECORDActionPerformed
    }
    private void jButton_ADDARECORDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ADDARECORDMouseEntered
        jButton_ADDARECORD.setForeground(Color.white);
        jButton_ADDARECORD.setBackground(Color.orange);
    }//GEN-LAST:event_jButton_ADDARECORDMouseEntered

    private void jButton_ADDARECORDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ADDARECORDMouseExited
         jButton_ADDARECORD.setForeground(Color.black);
        jButton_ADDARECORD.setBackground(Color.gray);
    }//GEN-LAST:event_jButton_ADDARECORDMouseExited

    private void jButton_UPDATEARECORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UPDATEARECORDActionPerformed
        String firstname=jTextField_FIRSTNAME.getText();
        String lastname=jTextField_LASTNAME.getText();
        String Gender=jRadioButton_MALE.getText();
        String RegEmpNo = jTextField_EmpRegNo.getText();
        
         String Email = jTextField_EMAILADRESS.getText();
       
        String Password=String.valueOf(jPasswordField_PASSWORD.getText());
        String Phone= jTextField_PHONENUMBER.getText();
        String Guardian_phone= jTextField_GUARDIANPHONE.getText();
       
       /* if (jTextField_FIRSTNAME.getText().trim().equals("") || jTextField_LASTNAME.getText().trim().equals("") || jRadioButton_MALE.getText().trim().equals("") || jTextField_EmpRegNo.getText().trim().equals("")
                || jTextField_EMAILADRESS.getText().trim().equals("")||jPasswordField_PASSWORD.getText().trim().equals("")||jTextField_PHONENUMBER.getText().trim().equals("")||jTextField_GUARDIANPHONE.getText().trim().equals("")) {

            JOptionPane.showMessageDialog(null, "One or more of the fields are Empty", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        }else*/
       
            try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/studentlogindata", "root", "");
           PreparedStatement ps=conn.prepareStatement("UPDATE registrationdetails SET fname=?,lname=?,Gender=?,Email=?,Password=?, Phone=?,GurdianNo=? WHERE RegEmpNo=?");
           ps.setString(1,firstname );
           ps.setString(2,lastname );
           ps.setString(3,Gender);
           ps.setString(4,Email );
           //ps.setString(5,Gendr );
           //ps.setString(5,RegNo );
           ps.setString(5, Password );
           ps.setString(6,Phone );
           ps.setString(7,Guardian_phone );
           ps.setString(8,RegEmpNo );
           

           
           if(jRadioButton_MALE.isSelected()){
           ps.setString(3, jRadioButton_MALE.getText());
           }else ps.setString(3, jRadioButton_FEMALE.getText());
           
           ps.execute();
           JOptionPane.showMessageDialog(this, "Details updated successfully");
           ps.close();
           conn.close();
           
           
                   
        }
       catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Registration or Employee number is required to update the records", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_UPDATEARECORDActionPerformed

    private void jButton_UPDATEARECORDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UPDATEARECORDMouseEntered
        jButton_UPDATEARECORD.setForeground(Color.white);
        jButton_UPDATEARECORD.setBackground(Color.green);
    }//GEN-LAST:event_jButton_UPDATEARECORDMouseEntered

    private void jButton_UPDATEARECORDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UPDATEARECORDMouseExited
         jButton_UPDATEARECORD.setForeground(Color.black);
        jButton_UPDATEARECORD.setBackground(Color.gray);
    }//GEN-LAST:event_jButton_UPDATEARECORDMouseExited

    private void jTextField_FIRSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FIRSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FIRSTNAMEActionPerformed

    private void jTextField_LASTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LASTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LASTNAMEActionPerformed

    private void jTextField_EmpRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmpRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmpRegNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton_ADDARECORD;
    private javax.swing.JButton jButton_CLEARTEXT;
    private javax.swing.JButton jButton_DELETEARECORD;
    private javax.swing.JButton jButton_UPDATEARECORD;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_PASSWORD;
    private javax.swing.JRadioButton jRadioButton_FEMALE;
    private javax.swing.JRadioButton jRadioButton_MALE;
    private javax.swing.JTextField jTextField_EMAILADRESS;
    private javax.swing.JTextField jTextField_EmpRegNo;
    private javax.swing.JTextField jTextField_FIRSTNAME;
    private javax.swing.JTextField jTextField_GUARDIANPHONE;
    private javax.swing.JTextField jTextField_LASTNAME;
    private javax.swing.JTextField jTextField_PHONENUMBER;
    // End of variables declaration//GEN-END:variables
}
